# Generated by Django 3.2.12 on 2022-02-18 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('classification', models.CharField(max_length=150)),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('eid', models.CharField(max_length=100)),
                ('sys_name', models.CharField(max_length=100)),
                ('characteristics', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_test_api.projects')),
            ],
        ),
    ]
